// <auto-generated />
using Kaffemaschine.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kaffemaschine.Migrations
{
    [DbContext(typeof(KaffeemaschineContext))]
    [Migration("20220603131706_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Kaffemaschine.Kaffeemaschine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("GesamtMengeKaffeProduziert")
                        .HasColumnType("REAL");

                    b.Property<double>("Kaffebohnen")
                        .HasColumnType("REAL");

                    b.Property<double>("Wasser")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Kaffeemaschine", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
